####### Link routes

### Returns all links from a user by id

GET http://localhost:3000/admin/links/all/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Returns all links from a user by username

GET http://localhost:3000/links/paulohos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Returns a single link

GET http://localhost:3000/admin/links/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Creates a link

POST http://localhost:3000/admin/links
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

{
    "title": "Google",
    "url": "www.google.com.br",
    "userId": 1
}

### Updates a link

PATCH http://localhost:3000/admin/links/1
Content-Type: application/json

{
    "title": "Updated Link",
    "url": "www.google.com.br",
    "userId": 1234
}

### Deletes a link

DELETE http://localhost:3000/admin/links/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

####### User routes

### Returns all users

GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Returns a single user

GET http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Creates a user

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Paulo Henrique",
    "username": "paulohos",
    "email": "test@gmail.com",
    "password": "Teste123"
}

### Updates a user

PATCH http://localhost:3000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

{
    "name": "Paulo",
    "username": "paulohos",
    "email": "teste@gmail.com"
}

### Deletes a user

DELETE http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3NTAwNDA5NDMsImV4cCI6MTc1MDA0MTAwM30.1P7EcT2-0qP2m1Zn09UHfyrJxIjQOmU5SThWmEXi61g

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "Test123"
}